"""The agent's shared state.

Every node receives this and returns a partial update; LangGraph merges the
updates. Modelling it explicitly — rather than passing a free-form dict —
means a node cannot invent a key, and the flow of evidence through the graph
is readable from one file.

Two design rules:

* **Nodes never mutate state in place.** Each returns a dict of the keys it
  changed. LangGraph applies those, which keeps concurrent branches safe and
  makes every state transition inspectable in the trace.
* **Facts and interpretation are separated.** `datasets`, `owners`,
  `lineage`, and `statistics` are raw Tool-layer output. `risk_score`,
  `risk_level`, and `findings` are computed deterministically by the risk
  engine. `summary`, `business_impact`, and `next_steps` are the only fields
  the LLM writes — so it is always obvious which parts of an answer were
  derived and which were generated.
"""

from __future__ import annotations

import time
from enum import StrEnum
from typing import Annotated, Any, TypedDict

from pydantic import BaseModel, ConfigDict, Field


class Intent(StrEnum):
    """What the user is asking for. Drives which nodes run."""

    FIND_MISSING_OWNERS = "find_missing_owners"
    ANALYZE_GOVERNANCE = "analyze_governance"
    ANALYZE_LINEAGE = "analyze_lineage"
    FIND_RISKY_DATASETS = "find_risky_datasets"
    GENERATE_DOCUMENTATION = "generate_documentation"
    GENERATE_REPORT = "generate_report"
    UNKNOWN = "unknown"


class RiskLevel(StrEnum):
    """Severity band derived from the numeric score. Never chosen by the LLM."""

    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


class NodeStatus(StrEnum):
    OK = "ok"
    SKIPPED = "skipped"
    FAILED = "failed"


class TraceEntry(BaseModel):
    """One node execution, for observability and for the UI timeline."""

    model_config = ConfigDict(frozen=True)

    node: str
    status: NodeStatus
    duration_ms: float
    detail: str = ""
    #: Set when the node failed. The graph continues; this records why.
    error: str | None = None

    @property
    def is_slow(self) -> bool:
        return self.duration_ms > 2000


class Finding(BaseModel):
    """One deterministic governance violation.

    Produced only by the risk engine. The `rule` and `points` fields make the
    score auditable: a reader can add the points up by hand and check the
    engine's arithmetic, which is the whole reason risk is not an LLM job.
    """

    model_config = ConfigDict(frozen=True)

    rule: str
    title: str
    severity: RiskLevel
    points: int
    asset_urn: str | None = None
    asset_name: str | None = None
    detail: str = ""


class Recommendation(BaseModel):
    """A corrective action. Generated by the LLM, bounded by the findings."""

    model_config = ConfigDict(frozen=True)

    action: str
    rationale: str
    priority: RiskLevel = RiskLevel.MEDIUM
    asset_urn: str | None = None


def _merge_traces(
    existing: list[TraceEntry] | None, incoming: list[TraceEntry] | None
) -> list[TraceEntry]:
    """Reducer: traces accumulate across nodes instead of overwriting.

    Without this, each node's returned `trace` would replace the previous
    one and the execution history would be a single entry.
    """
    return [*(existing or []), *(incoming or [])]


class AgentState(TypedDict, total=False):
    """State threaded through the graph.

    `total=False` because nodes fill it progressively — the planner has run
    before `datasets` exists, and `risk_score` only after the risk node.
    """

    # --- Input -----------------------------------------------------------------
    question: str

    # --- Planner output --------------------------------------------------------
    intent: Intent
    #: Node names the planner selected. The router consults this, so skipping
    #: a tool is a planning decision rather than logic buried in a node.
    plan: list[str]
    plan_reason: str
    #: Optional URN extracted from the question, when the user named an asset.
    target_urn: str | None
    target_name: str | None

    # --- Tool-layer facts (deterministic) --------------------------------------
    datasets: list[dict[str, Any]]
    owners: list[dict[str, Any]]
    lineage: dict[str, Any]
    statistics: dict[str, Any]

    # --- Risk engine output (deterministic) ------------------------------------
    risk_score: int
    risk_level: RiskLevel
    findings: list[Finding]
    evidence: list[dict[str, Any]]

    # --- LLM output ------------------------------------------------------------
    summary: str
    business_impact: str
    recommendations: list[Recommendation]
    next_steps: list[str]

    # --- Observability ---------------------------------------------------------
    trace: Annotated[list[TraceEntry], _merge_traces]
    errors: Annotated[list[str], _merge_traces]
    started_at: float
    llm_provider: str
    llm_latency_ms: float
    #: True when a tool or the LLM failed and the answer is built from partial
    #: data. Surfaced to the caller so a degraded answer is never mistaken for
    #: a complete one.
    degraded: bool


def new_state(question: str) -> AgentState:
    """Seed state for a run."""
    return AgentState(
        question=question,
        started_at=time.perf_counter(),
        datasets=[],
        owners=[],
        lineage={},
        statistics={},
        findings=[],
        evidence=[],
        recommendations=[],
        next_steps=[],
        trace=[],
        errors=[],
        degraded=False,
        risk_score=0,
        risk_level=RiskLevel.LOW,
    )


class AgentResult(BaseModel):
    """The response contract, matching the documented JSON shape."""

    model_config = ConfigDict(frozen=True)

    question: str
    intent: Intent
    summary: str
    risk_level: RiskLevel
    risk_score: int
    findings: list[Finding] = Field(default_factory=list)
    recommendations: list[Recommendation] = Field(default_factory=list)
    evidence: list[dict[str, Any]] = Field(default_factory=list)
    business_impact: str = ""
    next_steps: list[str] = Field(default_factory=list)

    # --- Execution metadata ----------------------------------------------------
    trace: list[TraceEntry] = Field(default_factory=list)
    errors: list[str] = Field(default_factory=list)
    degraded: bool = False
    duration_ms: float = 0.0
    llm_provider: str = ""
    tools_used: list[str] = Field(default_factory=list)
